services:
  watchdog:

    build:

      context: .

    command: python3 bot/watchdog.py

    volumes:

      - .:/app

      - /var/run/docker.sock:/usr/bin/docker

    restart: always
  trader:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    restart: always
    command: python3 -m bot.core
